apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-resource-nginx-tls
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  tls:
  - hosts:
    - bench-ingress-nginx.example.com
    secretName: cert-nginx-ssl
  rules:
    - host: bench-ingress-nginx.example.com
      http:
        paths:
        - path: /hello
          pathType: Prefix
          backend:
            service:
              name: hello-server
              port:
                number: 8080
